# -*- coding: utf-8 -*-
"""dataMining_FeatureTransformation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iKMnx2giknF60XaU82gy59RxLryyanhJ
"""

import pandas as pd
import numpy as np

d1 = {
    'ID':[1,2,3,4,5],
    'Name': ['Alice', 'Bob', 'Charlie', 'David','Rohan'],
    'Age':[20,25,30,40,35]
}

d2 = {
    'ID':[3,4,5,6,7],
    'Gender': ['F','M','M','F','M'],
    'Salary':[70000,80000,60000,50000,75000]
}
df1 = pd.DataFrame(d1)
df2 = pd.DataFrame(d2)

# Data Integration
## Tight Coupling (Join datasets on a common key)
tight_coupling = pd.merge(df1,df2,on='ID',how='inner')
print("Tight Coupling Result:\n",tight_coupling)

## Loose Coupling (Concatenate datasets)
loose_coupling = pd.concat([df1.set_index('ID'), df2.set_index('ID')], axis=1).reset_index()
print("Loose Coupling Result:\n", loose_coupling)

# Data Transformation
## Smoothing (Moving Average for Age)
loose_coupling['Smoothed_Age'] = loose_coupling['Age'].rolling(window=2, min_periods=1).mean()
print("\nSmoothing:\n", loose_coupling[['ID', 'Age', 'Smoothed_Age']])

## Aggregation (Summarizing Salary by Gender)
aggregation = loose_coupling.groupby('Gender')['Salary'].sum().reset_index()
print("\nAggregation:\n", aggregation)

## Discretization (Binning Age into Categories)
bins = [0, 20, 30, 40, 50]
labels = ['Teen', 'Young Adult', 'Adult', 'Senior']
loose_coupling['Age_Group'] = pd.cut(loose_coupling['Age'], bins=bins, labels=labels)
print("\nDiscretization:\n", loose_coupling[['ID', 'Age', 'Age_Group']])

# Attribute Construction (Creating Age-Salary Ratio)
loose_coupling['Age_Salary_Ratio'] = loose_coupling['Age'] / loose_coupling['Salary']
print("\nAttribute Construction:\n", loose_coupling[['ID', 'Age', 'Salary', 'Age_Salary_Ratio']])

# Generalization (Simplifying Salary into Ranges)
salary_bins = [0, 60000, 80000, 100000]
salary_labels = ['Low', 'Medium', 'High']
loose_coupling['Salary_Range'] = pd.cut(loose_coupling['Salary'], bins=salary_bins, labels=salary_labels)
print("\nGeneralization:\n", loose_coupling[['ID', 'Salary', 'Salary_Range']])

# Normalization
# Min-Max Normalization
loose_coupling['Age_MinMax'] = (loose_coupling['Age'] - loose_coupling['Age'].min()) / (loose_coupling['Age'].max() - loose_coupling['Age'].min())
print("\nMin-Max Normalization:\n", loose_coupling[['ID', 'Age', 'Age_MinMax']])

# Z-Score Normalization
loose_coupling['Age_ZScore'] = (loose_coupling['Age'] - loose_coupling['Age'].mean()) / loose_coupling['Age'].std()
print("\nZ-Score Normalization:\n", loose_coupling[['ID', 'Age', 'Age_ZScore']])

### Decimal Scaling
scaling_factor = 10 ** np.ceil(np.log10(loose_coupling['Age'].abs().max()))
loose_coupling['Age_DecimalScaling'] = loose_coupling['Age'] / scaling_factor
print("\nDecimal Scaling:\n", loose_coupling[['ID', 'Age', 'Age_DecimalScaling']])

