# -*- coding: utf-8 -*-
"""Feature_Transformation_DataMining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yCbM_DvQ_CPU4JlncrwJPocR6q6147ot

There are 3 types of Feature transformation techniques:

Function Transformers

Power Transformers

Quantile Transformers

Function Transformers

Function transformers are the type of feature transformation technique that uses a particular function to transform the data to the normal distribution. Here the particular function is applied to the data observations.

There is not any thumb rule for the selection of function transformers, the function can be designed by anyone good at domain knowledge of the data, but mostly there are 5 types of function transformers that are used and which also solve the issue of normal distribution almost every time.

Log Transform

Square Transform

Square Root Transform

Reciprocal Transform

Custom Transform

1.Log Transform

Log transform is one of the simplest transformations on the data in which the log is applied to every single distribution of the data and the result from the log is considered the final day to feed the machine learning algorithms.

Through experiments, it is proven that log transforms performs so well on the right-skewed data. It transforms the right-skewed data into normally distributed data so well.

2.Square Transform

Square transform is the type of transformer in which the square of the data is considered instead of the normal data. In simple words, in this transformed the data is applied with the square function, where the square of every single observation will be considered as the final transformed data.

3.Square Root Transform

In this transform, the square root of the data is calculated. This transform performs so well on the left-skewed data and efficiently transformed the left-skewed data into normally distributed data.

4.Reciprocal Transform

In this transformation, the reciprocal of every observation is considered. This transform is useful in some of the datasets as the reciprocal of the observations works well to achieve normal distributions.

5.Custom Transforms

In every dataset, the log and square root transforms can not be used, as every data can have different patterns and complexity. Based on the domain knowledge of the data, custom transformations can be applied to transform the data into a normal distribution. The custom transforms here can be any function or parameter like sin, cos, tan, cube, etc.
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import FunctionTransformer

# Step 1: Create sample data
data = np.array([1,2,3,4,5,6],dtype=float)

# Logarithmic transformation
transform = FunctionTransformer(func = np.log1p)
log_transformed_data = transform.fit_transform(data)

# Square transformation
square_transformed_data = np.square(data)

# Reciprocal transformation
reciprocal_transformed_data = np.reciprocal(data)

# Trigonometric transformations (custom_
sin_transformed_data = np.sin(data)
cos_transformed_data = np.cos(data)
tan_transformed_data = np.tan(data)

# Square root transformation
sqrt_transformed_data = np.sqrt(data)

#Combine into a DataFrame for comparison
results = pd.DataFrame({
    'Original': data,
    'Logarithmic': log_transformed_data,
    'Square': square_transformed_data,
    'Reciprocal': reciprocal_transformed_data,
    'Sin': sin_transformed_data,
    'Cos': cos_transformed_data,
    'Tan': tan_transformed_data,
    'Square Root': sqrt_transformed_data
})

print(results)

