# -*- coding: utf-8 -*-
"""Feature_Selection_DataMining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_rzgZ39wJNU7BpG4UawBL4n3cjltpPWi
"""

import numpy as np
import pandas as pd
from sklearn.datasets import load_wine
from sklearn.feature_selection import SelectKBest,chi2,f_classif,VarianceThreshold,RFE
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, LassoCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from mlxtend.feature_selection import SequentialFeatureSelector

wine = load_wine()
x = pd.DataFrame(wine.data,columns=wine.feature_names)
y = pd.Series(wine.target)

x.head()

y.head()

# Display the first few rows of the dataset
print("Sample DataFrame:")
print(x.head())

# Normalize the data
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)
x_scaled = pd.DataFrame(x_scaled, columns=x.columns)

# 1. Filter Methods
print("\n=== Filter Methods ===")

# Information Gain (ANOVA F-value for classification)
f_scores, _ = f_classif(x_scaled, y)
info_gain = pd.Series(f_scores, index=x.columns)
print("Top features by Information Gain:")
print(info_gain.sort_values(ascending=False).head())

# Chi-square test
chi_scores, _ = chi2(np.abs(x_scaled), y)
chi2_scores = pd.Series(chi_scores, index=x.columns)
print("\nTop features by Chi-square test:")
print(chi2_scores.sort_values(ascending=False).head())

# Correlation Coefficient
correlations = x.corrwith(y)
print("\nTop features by Correlation Coefficient:")
print(correlations.abs().sort_values(ascending=False).head())

# Variance Threshold
vt = VarianceThreshold(threshold=0.01)
vt.fit(x)
var_features = x.columns[vt.get_support()]
print("\nFeatures selected by Variance Threshold:")
print(var_features)

# Mean Absolute Difference (MAD)
mad_scores = x.apply(lambda col: np.mean(np.abs(col - np.mean(col))))
print("\nTop features by Mean Absolute Difference (MAD):")
print(mad_scores.sort_values(ascending=False).head())

# 2. Wrapper Methods
print("\n=== Wrapper Methods ===")

# Forward Selection
lr = LogisticRegression(max_iter=10000, random_state=0)
forward_selector = SequentialFeatureSelector(lr, k_features=5, forward=True, scoring='accuracy', cv=3)
forward_selector = forward_selector.fit(x_scaled, y)
print("\nFeatures selected by Forward Selection:")
print(forward_selector.k_feature_names_)

# Backward Elimination
backward_selector = SequentialFeatureSelector(lr, k_features=5, forward=False, scoring='accuracy', cv=3)
backward_selector = backward_selector.fit(x_scaled, y)
print("\nFeatures selected by Backward Elimination:")
print(backward_selector.k_feature_names_)

# Recursive Feature Elimination (RFE)
rfe = RFE(lr, n_features_to_select=5)
rfe.fit(x_scaled, y)
print("\nFeatures selected by RFE:")
print(x.columns[rfe.support_])

# 3. Embedded Methods
print("\n=== Embedded Methods ===")

# Regularization (Lasso)
lasso = LassoCV(cv=5, random_state=0).fit(x_scaled, y)
lasso_features = x.columns[lasso.coef_ != 0]
print("\nFeatures selected by Lasso Regularization:")
print(lasso_features)

# Tree-based method (Random Forest)
rf = RandomForestClassifier(random_state=0)
rf.fit(x_scaled, y)
importances = pd.Series(rf.feature_importances_, index=x.columns)
print("\nTop features by Tree-based method:")
print(importances.sort_values(ascending=False).head())











