# -*- coding: utf-8 -*-
"""PCA_DataMining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BD8JBAKov5qJd-jLfFjjXBmzSk4oMgzu
"""

import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns

cancer = load_breast_cancer(as_frame=True)
df = cancer.frame
df.head()

print('Original Dataframe shape:',df.shape)
x= df[cancer['feature_names']]
print('Input Dataframe shape:',x.shape)

"""####Now we will apply the first most step which is to standardize the data and for that, we will have to first calculate the mean and standard deviation of each feature in the feature space."""

x_mean = x.mean()
x_std = x.std()
z = (x-x_mean)/x_std
z

"""#####
The covariance matrix helps us visualize how strong the dependency of two features is with each other in the feature space.
"""

c = z.cov()
sns.heatmap(c)
plt.show

#Now we will compute the eigenvectors and eigenvalues for our feature space which serve a great purpose
#in identifying the principal components for our feature space.

eigenvalues,eigenvectors = np.linalg.eig(c)
print('Eigenvalues:',eigenvalues)
print('Eigenvalues Shapes:',eigenvalues.shape)
print('Eigenvectors Shapes:',eigenvectors.shape)

#Sort the eigenvalues in descending order and sort the corresponding eigenvectors accordingly.
# Index the eigenvalues in descending order
idx = eigenvalues.argsort()[::-1]
# Sort the eigenvalues in descending order
eigenvalues = eigenvalues[idx]
# sort the corresponding eigenvectors accordingly
eigenvectors = eigenvectors[:,idx]

#Explained variance is the term that gives us an idea of the amount of the total variance
#which has been retained by selecting the principal components instead of the original feature space.
explained_var = np.cumsum(eigenvalues) / np.sum(eigenvalues)
explained_var

#Determine the Number of Principal Components
#Here we can either consider the number of principal components of any value of our choice or by limiting
#the explained variance. Here I am considering explained variance more than equal to 50%. Let’s check how many principal components come into this.

n_components = np.argmax(explained_var >= 0.50) + 1
n_components

"""#### Project the Data onto the Selected Principal Components

Find the projection matrix, It is a matrix of eigenvectors corresponding to the largest eigenvalues of the covariance matrix of the data. it projects the high-dimensional dataset onto a lower-dimensional subspace

The eigenvectors of the covariance matrix of the data are referred to as the principal axes of the data, and the projection of the data instances onto these principal axes are called the principal components.
"""

#PCA component or unit matrix
u=eigenvectors[:,:n_components]
pca_component = pd.DataFrame(u,index=cancer['feature_names'],columns=['PC1','PC2'])

plt.figure(figsize=(10,6))
sns.heatmap(pca_component)
plt.title('PCA Component')
plt.show()

#Matrix multiplication or dot product
z_pca = z @ pca_component

#Rename the columns name
z_pca.rename({'PC1':'PCA1','PC2':'PCA2'},axis = 1, inplace = True)
#print the Principal Components
print(z_pca)

pca = PCA(n_components=2)
pca.fit(z)
x_pca = pca.transform(z)
df_pca1 = pd.DataFrame(x_pca,columns=['PC{}'.format(i+1) for i in range(n_components)])
print(df_pca1)

plt.figure(figsize=(10,6))
plt.scatter(x_pca[:,0],x_pca[:,1],c=cancer['target'],cmap='plasma')
plt.xlabel('First Principal Component (PC1)')
plt.ylabel('Second Principal Component (PC2)')
plt.show()

pca.components_

